name: CI/CD deploy release

on:
  push:
    branches:
      - "deploy-release"
  pull_request:
    branches:
      - "deploy-release"

jobs:
  ci_cd_deploy_release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo 'hello world'
      - name: Use Node.js 20.x
        uses: actions/setup-node@v1
        with:
          node-version: 20.x
      - name: Install dependencies
        run: npm ci
      - name: Build setup
        run: npm run build
      - name: List dir
        run: ls -la dist/mycv2/browser
      - name: Copy index.html, css, js
        run: cp dist/mycv2/browser/*.* docs
      - name: List docs
        run: ls -la docs
      - name: GIT commit and push docs
        env: 
          CI_COMMIT_MESSAGE: save spark results
          CI_COMMIT_AUTHOR: adsoft 
        run: |
          git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
          git config --global user.email "joseantonioortizhernandez777@gmail.com"
          git add docs
          git commit -m "${{ env.CI_COMMIT_MESSAGE }}"
          git push
