name: Deploy Angular App to GitHub Pages

on:
  push:
    branches:
      - deploy-release  # Cambia esto si tu rama es distinta
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install

      - name: Build Angular app
        run: |
          npm install -g @angular/cli
          ng build --configuration production --base-href "/mycv2_joshi/"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: dist/mycv2

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

